use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("python");
    fs::create_dir_all(&dest).unwrap();
    fs::create_dir_all(dest.join("ocs")).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=ocs/__init__.py");

    write_repl_wrapper(&dest);
    write_startup(&dest);
    write_ocs_init(&dest);
    write_entities(&dest);
    write_entities_stub(&dest);
    write_ocs_stub(&dest);
    write_py_typed(&dest);
}

fn write_file(path: &std::path::Path, content: &str) {
    fs::write(path, content).unwrap();
}

fn write_repl_wrapper(dest: &std::path::Path) {
    let content = r##"# Generated by ocs_python_repl/build.rs
"""Platform wrapper that launches IPython (or plain Python) in an OS terminal."""
import os
import shlex
import shutil
import signal
import subprocess
import sys
import time
import traceback

SESSION_DIR = os.path.dirname(os.path.abspath(__file__))
PYTHON = sys.executable
LOG_PATH = os.path.join(SESSION_DIR, "repl.log")
STDERR_LOG_PATH = os.path.join(SESSION_DIR, "wrapper_stderr.log")

# Redirect the wrapper's Python-level stderr to a log file so the host can read
# startup errors. On Windows the wrapper console is hidden from the start.
try:
    sys.stderr = open(STDERR_LOG_PATH, "a", encoding="utf-8")
except Exception:
    pass


def log(msg):
    try:
        with open(LOG_PATH, "a", encoding="utf-8") as f:
            f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} {msg}\n")
    except Exception:
        pass


log(f"wrapper started: python={PYTHON} platform={sys.platform}")


def check_ipython():
    try:
        subprocess.run(
            [PYTHON, "-c", "import IPython"],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return True
    except Exception:
        return False


def make_env():
    env = os.environ.copy()
    parts = env.get("PYTHONPATH", "").split(os.pathsep)
    if SESSION_DIR not in parts:
        parts.insert(0, SESSION_DIR)
    env["PYTHONPATH"] = os.pathsep.join(parts)
    return env


def start_ipython_command():
    startup = os.path.join(SESSION_DIR, "startup.py")
    return [PYTHON, "-m", "IPython", "-i", startup]


def start_plain_command():
    startup = os.path.join(SESSION_DIR, "startup.py")
    return [PYTHON, "-i", startup]


def find_terminal():
    candidates = [
        "xterm",
        "konsole",
        "xfce4-terminal",
        "gnome-terminal",
        "alacritty",
        "kitty",
        "wezterm",
    ]
    for name in candidates:
        if shutil.which(name):
            return name
    if sys.platform == "darwin" and os.path.isdir(
        "/System/Applications/Utilities/Terminal.app"
    ):
        return "Terminal.app"
    return None


def build_terminal_command(term, cmd):
    if term == "xterm":
        return ["xterm", "-e"] + cmd
    if term == "konsole":
        return ["konsole", "-e"] + cmd
    if term == "xfce4-terminal":
        return ["xfce4-terminal", "-e", " ".join(shlex.quote(c) for c in cmd)]
    if term == "gnome-terminal":
        return ["gnome-terminal", "--"] + cmd
    if term == "alacritty":
        return ["alacritty", "-e"] + cmd
    if term == "kitty":
        return ["kitty"] + cmd
    if term == "wezterm":
        return ["wezterm", "start", "--"] + cmd
    raise RuntimeError(f"unsupported terminal: {term}")


def spawn_terminal_app(cmd, env):
    """Best-effort Terminal.app support on macOS."""
    import tempfile

    script = tempfile.NamedTemporaryFile(mode="w", suffix=".command", delete=False)
    pid_file = script.name + ".pid"

    def _cleanup():
        try:
            os.unlink(pid_file)
        except FileNotFoundError:
            pass
        except Exception:
            pass
        try:
            os.unlink(script.name)
        except FileNotFoundError:
            pass
        except Exception:
            pass

    try:
        script.write("#!/bin/sh\n")
        script.write(f"echo $$ > {shlex.quote(pid_file)}\n")
        for key, value in env.items():
            script.write(f"export {shlex.quote(key)}={shlex.quote(value)}\n")
        script.write("cd " + shlex.quote(SESSION_DIR) + "\n")
        script.write(" ".join(shlex.quote(c) for c in cmd) + "\n")
        script.write(f"rm -f {shlex.quote(pid_file)}\n")
        script.write(f"rm -f {shlex.quote(script.name)}\n")
        script.close()
        os.chmod(script.name, 0o755)

        try:
            subprocess.Popen(
                ["open", "-a", "Terminal.app", script.name], env=env
            )
        except Exception as e:
            print(f"failed to launch Terminal.app: {e}", file=sys.stderr)
            _cleanup()
            return _DummyProcess()

        # Wait for the shell inside Terminal.app to write its PID.
        for _ in range(50):
            if os.path.exists(pid_file):
                break
            time.sleep(0.1)

        if not os.path.exists(pid_file):
            _cleanup()
            return _DummyProcess()

        pid = int(open(pid_file).read())

        class Proc:
            def terminate(self):
                _kill_pid(pid, signal.SIGTERM)

            def kill(self):
                _kill_pid(pid, signal.SIGKILL)

            def wait(self):
                while True:
                    try:
                        os.kill(pid, 0)
                    except ProcessLookupError:
                        break
                    time.sleep(0.5)
                _cleanup()
                return 0

        return Proc()
    except Exception:
        _cleanup()
        raise


class _DummyProcess:
    def terminate(self):
        pass

    def kill(self):
        pass

    def wait(self):
        while True:
            time.sleep(1)


def _kill_pid(pid, sig):
    try:
        os.kill(pid, sig)
    except ProcessLookupError:
        pass
    except Exception:
        pass


def spawn_unix(cmd, env):
    term = find_terminal()
    if term is None:
        sys.exit(
            "No terminal emulator found. "
            "Install xterm, konsole, xfce4-terminal, gnome-terminal, alacritty, kitty, or wezterm."
        )
    if term == "Terminal.app":
        return spawn_terminal_app(cmd, env)
    return subprocess.Popen(build_terminal_command(term, cmd), env=env)


def install_signal_handlers(proc):
    def handler(signum, frame):
        try:
            proc.terminate()
        except Exception:
            pass
        try:
            proc.kill()
        except Exception:
            pass
        sys.exit(0)

    signal.signal(signal.SIGTERM, handler)
    signal.signal(signal.SIGINT, handler)


def main():
    try:
        if check_ipython():
            cmd = start_ipython_command()
            log("using IPython")
        else:
            log("IPython not found; falling back to plain Python REPL")
            print(
                "IPython not found; falling back to plain Python REPL.", file=sys.stderr
            )
            cmd = start_plain_command()

        env = make_env()
        log(f"command: {cmd}")
        log(f"PYTHONPATH: {env.get('PYTHONPATH', '')}")

        if sys.platform == "win32":
            # The wrapper has a hidden console created by the Rust host, so
            # subprocess.Popen inherits real console handles. CREATE_NEW_CONSOLE
            # gives IPython its own visible console where Ctrl+C works.
            CREATE_NEW_CONSOLE = 0x00000010
            proc = subprocess.Popen(cmd, env=env, creationflags=CREATE_NEW_CONSOLE)
            log(f"spawned windows process pid={proc.pid}")
        else:
            proc = spawn_unix(cmd, env)
            install_signal_handlers(proc)
            log(f"spawned unix process pid={proc.pid}")

        try:
            code = proc.wait()
            log(f"child exited with code {code}")
        except KeyboardInterrupt:
            log("keyboard interrupt")
            code = 0
        sys.exit(code)
    except Exception as e:
        log(f"wrapper crashed: {e}\n{traceback.format_exc()}")
        raise


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
        sys.exit(1)
"##;
    write_file(&dest.join("repl_wrapper.py"), content);
}

fn write_startup(dest: &std::path::Path) {
    let content = r##"# Generated by ocs_python_repl/build.rs
"""Bootstrap the IPython REPL with OCS document access and magics."""
import os
import re
import shlex
import sys

_SESSION_DIR = os.path.dirname(os.path.abspath(__file__))
if _SESSION_DIR not in sys.path:
    sys.path.insert(0, _SESSION_DIR)

import ocs

_snapshot_path = os.environ.get("OCS_V4_SNAPSHOT", "")
ocs.doc = ocs._init(_snapshot_path)


def _pyimport(path):
    """Run a Python script in the current namespace."""
    if not os.path.isfile(path):
        print(f"pyimport: file not found: {path}", file=sys.stderr)
        return
    with open(path, "r", encoding="utf-8") as f:
        code = f.read()
    exec(code, globals())


def _pyexport(path):
    """Write the current session's input history to a file."""
    content = "# No input history available in plain Python REPL.\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Exported session to {path}")


try:
    from IPython.core.magic import register_line_magic

    @register_line_magic
    def pyimport(line):
        path = line.strip().strip('"').strip("'")
        if not os.path.isfile(path):
            print(f"pyimport: file not found: {path}", file=sys.stderr)
            return
        get_ipython().run_line_magic("run", f"-i {shlex.quote(path)}")

    @register_line_magic
    def pyexport(line):
        path = line.strip().strip('"').strip("'")
        hist = list(get_ipython().history_manager.get_range())
        cells = []
        for _session, _line, cell in hist:
            cell = cell.strip()
            if cell.startswith("%pyexport"):
                continue
            # Strip IPython continuation prompts.
            cell = re.sub(r"^\s*\.{3,}\s?", "", cell, flags=re.MULTILINE)
            cells.append(cell)
        if cells:
            content = "\n".join(cells) + "\n"
        else:
            content = "# No input history to export.\n"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Exported session to {path}")

except Exception:
    # Plain Python REPL fallback.
    def pyimport(path):
        _pyimport(path)

    def pyexport(path):
        _pyexport(path)
"##;
    write_file(&dest.join("startup.py"), content);
}

fn write_ocs_init(dest: &std::path::Path) {
    let content = r##"# Open CAD Studio Python REPL package.
# The compiled Rust extension is loaded as `ocs_python_repl` and re-exported
# under the `ocs` namespace. Generated entity classes live in `ocs.entities`.
#
# Implementation note: we replace `sys.modules[__name__]` with the extension
# module object so that `import ocs` gives users the Rust-backed `_OcsDocument`
# directly. We then set `__path__` so that `ocs.entities` still resolves to the
# generated submodule for editor tooling and type checkers.

import os
import shutil
import sys

_package_dir = os.path.dirname(os.path.abspath(__file__))
_parent_dir = os.path.dirname(_package_dir)
if _parent_dir not in sys.path:
    sys.path.insert(0, _parent_dir)

def _load_extension():
    """Load the Rust extension, coping with Windows refusing `.dll` imports."""
    try:
        import ocs_python_repl as _ocs  # type: ignore
        return _ocs
    except ImportError:
        pass

    _cdylib_path = os.environ.get("OCS_PLUGIN_CDYLIB_PATH", "")
    if not _cdylib_path or not os.path.isfile(_cdylib_path):
        raise ImportError(
            "The OCS Python extension (ocs_python_repl) is not available. "
            "Make sure the Python REPL plugin is loaded and the plugin directory "
            "is on PYTHONPATH."
        )

    # On Windows, Python's import machinery only recognises `.pyd` as an
    # extension-module suffix. Copy/hardlink the cdylib into the session dir
    # with the expected name so normal import succeeds.
    _pyd_path = os.path.join(_parent_dir, "ocs_python_repl.pyd")
    if not os.path.isfile(_pyd_path):
        try:
            os.link(_cdylib_path, _pyd_path)
        except Exception:
            shutil.copy2(_cdylib_path, _pyd_path)
    import ocs_python_repl as _ocs  # type: ignore
    return _ocs

_ocs = _load_extension()

sys.modules[__name__] = _ocs

# Keep the package path resolvable for editor tooling.
if not hasattr(_ocs, "__path__"):
    _ocs.__path__ = [_package_dir]
"##;
    write_file(&dest.join("ocs/__init__.py"), content);
}

fn write_entities(dest: &std::path::Path) {
    let content = r#"# Generated by ocs_python_repl/build.rs
from dataclasses import dataclass, field
from typing import Optional, List, Tuple, Union

@dataclass
class Vector2:
    x: float = 0.0
    y: float = 0.0

@dataclass
class Vector3:
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0

@dataclass
class Color:
    """AutoCAD color value.

    For special colors use kind="ByLayer", "ByBlock", or "None".
    For an indexed color use kind="Index" and index=1..255.
    For an RGB color use kind="Rgb" and r/g/b=0..255.
    """
    kind: str = "ByLayer"
    index: int = 0
    r: int = 0
    g: int = 0
    b: int = 0

@dataclass
class LayerFlags:
    frozen: bool = False
    locked: bool = False
    frozen_in_new_viewport: bool = False
    off: bool = False
    xref_dependent: bool = False

@dataclass
class Layer:
    """Layer table entry (not an entity)."""
    handle: int = 0
    name: str = "0"
    flags: LayerFlags = field(default_factory=LayerFlags)
    color: Color = field(default_factory=Color)
    line_type: str = "Continuous"
    line_weight: str = "ByLayer"
    plot_style: str = ""
    is_plottable: bool = True
    transparency: int = 0
    material: int = 0
    plotstyle_handle: int = 0
    xref_block_record_handle: int = 0

@dataclass
class XDataValue:
    """Extended data value used in XDATA records."""
    kind: str = "String"
    value: Union[str, bytes, int, float, Tuple[float, float, float]] = ""

@dataclass
class Entity:
    handle: int = 0
    layer: str = "0"

@dataclass
class Point(Entity):
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0
    thickness: float = 0.0
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)
    x_axis_angle: float = 0.0

@dataclass
class Line(Entity):
    start: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    end: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    thickness: float = 0.0
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)

@dataclass
class Circle(Entity):
    center: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    radius: float = 1.0
    thickness: float = 0.0
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)

@dataclass
class Arc(Entity):
    center: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    radius: float = 1.0
    start_angle: float = 0.0
    end_angle: float = 0.0
    thickness: float = 0.0
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)

@dataclass
class Ellipse(Entity):
    center: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    major_axis: Tuple[float, float, float] = (1.0, 0.0, 0.0)
    minor_axis_ratio: float = 0.5
    start_parameter: float = 0.0
    end_parameter: float = 6.283185307179586
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)

@dataclass
class Polyline(Entity):
    points: List[Tuple[float, float, float]] = field(default_factory=list)
    closed: bool = False

@dataclass
class Polyline2D(Entity):
    points: List[Tuple[float, float, float]] = field(default_factory=list)
    closed: bool = False
    smooth_surface: str = "None"
    start_width: float = 0.0
    end_width: float = 0.0
    thickness: float = 0.0
    elevation: float = 0.0
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)

@dataclass
class Polyline3D(Entity):
    points: List[Tuple[float, float, float]] = field(default_factory=list)
    closed: bool = False
    spline_fit: bool = False
    is_3d_mesh: bool = False
    mesh_closed_n: bool = False
    is_polyface_mesh: bool = False
    linetype_continuous: bool = False
    smooth_type: str = "None"
    default_start_width: float = 0.0
    default_end_width: float = 0.0
    mesh_m_count: int = 0
    mesh_n_count: int = 0
    smooth_m_density: int = 0
    smooth_n_density: int = 0
    elevation: float = 0.0
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)

@dataclass
class LwPolyline(Entity):
    points: List[Tuple[float, float, float]] = field(default_factory=list)
    closed: bool = False
    plinegen: bool = False
    constant_width: float = 0.0
    elevation: float = 0.0
    thickness: float = 0.0
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)

@dataclass
class Spline(Entity):
    degree: int = 3
    closed: bool = False
    periodic: bool = False
    rational: bool = False
    planar: bool = False
    linear: bool = False
    knots: List[float] = field(default_factory=list)
    control_points: List[Tuple[float, float, float]] = field(default_factory=list)
    weights: List[float] = field(default_factory=list)
    fit_points: List[Tuple[float, float, float]] = field(default_factory=list)
    normal: Tuple[float, float, float] = (0.0, 0.0, 1.0)
    knot_tolerance: float = 1e-7
    control_tolerance: float = 1e-7
    fit_tolerance: float = 1e-10
    begin_tangent: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    end_tangent: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    knot_parameterization: int = 0
    cv_frame_visible: bool = False
    dwg_flags1: int = 0

@dataclass
class MText(Entity):
    text: str = ""
    insertion: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    height: float = 1.0

# Mapping from acadrust EntityType variant name to Python class.
KIND_MAP = {
    "Point": Point,
    "Line": Line,
    "Circle": Circle,
    "Arc": Arc,
    "Ellipse": Ellipse,
    "Polyline": Polyline,
    "Polyline2D": Polyline2D,
    "Polyline3D": Polyline3D,
    "LwPolyline": LwPolyline,
    "Spline": Spline,
    "MText": MText,
}
"#;
    write_file(&dest.join("ocs/entities.py"), content);
}

fn write_entities_stub(dest: &std::path::Path) {
    let content = r#"# Generated by ocs_python_repl/build.rs
from dataclasses import dataclass
from typing import List, Tuple, Union

class Vector2:
    x: float
    y: float

class Vector3:
    x: float
    y: float
    z: float

class Color:
    kind: str
    index: int
    r: int
    g: int
    b: int

class LayerFlags:
    frozen: bool
    locked: bool
    frozen_in_new_viewport: bool
    off: bool
    xref_dependent: bool

class Layer:
    handle: int
    name: str
    flags: LayerFlags
    color: Color
    line_type: str
    line_weight: str
    plot_style: str
    is_plottable: bool
    transparency: int
    material: int
    plotstyle_handle: int
    xref_block_record_handle: int

class XDataValue:
    kind: str
    value: Union[str, bytes, int, float, Tuple[float, float, float]]

class Entity:
    handle: int
    layer: str

class Point(Entity):
    x: float
    y: float
    z: float
    thickness: float
    normal: Tuple[float, float, float]
    x_axis_angle: float

class Line(Entity):
    start: Tuple[float, float, float]
    end: Tuple[float, float, float]
    thickness: float
    normal: Tuple[float, float, float]

class Circle(Entity):
    center: Tuple[float, float, float]
    radius: float
    thickness: float
    normal: Tuple[float, float, float]

class Arc(Entity):
    center: Tuple[float, float, float]
    radius: float
    start_angle: float
    end_angle: float
    thickness: float
    normal: Tuple[float, float, float]

class Ellipse(Entity):
    center: Tuple[float, float, float]
    major_axis: Tuple[float, float, float]
    minor_axis_ratio: float
    start_parameter: float
    end_parameter: float
    normal: Tuple[float, float, float]

class Polyline(Entity):
    points: List[Tuple[float, float, float]]
    closed: bool

class Polyline2D(Entity):
    points: List[Tuple[float, float, float]]
    closed: bool
    smooth_surface: str
    start_width: float
    end_width: float
    thickness: float
    elevation: float
    normal: Tuple[float, float, float]

class Polyline3D(Entity):
    points: List[Tuple[float, float, float]]
    closed: bool
    spline_fit: bool
    is_3d_mesh: bool
    mesh_closed_n: bool
    is_polyface_mesh: bool
    linetype_continuous: bool
    smooth_type: str
    default_start_width: float
    default_end_width: float
    mesh_m_count: int
    mesh_n_count: int
    smooth_m_density: int
    smooth_n_density: int
    elevation: float
    normal: Tuple[float, float, float]

class LwPolyline(Entity):
    points: List[Tuple[float, float, float]]
    closed: bool
    plinegen: bool
    constant_width: float
    elevation: float
    thickness: float
    normal: Tuple[float, float, float]

class Spline(Entity):
    degree: int
    closed: bool
    periodic: bool
    rational: bool
    planar: bool
    linear: bool
    knots: List[float]
    control_points: List[Tuple[float, float, float]]
    weights: List[float]
    fit_points: List[Tuple[float, float, float]]
    normal: Tuple[float, float, float]
    knot_tolerance: float
    control_tolerance: float
    fit_tolerance: float
    begin_tangent: Tuple[float, float, float]
    end_tangent: Tuple[float, float, float]
    knot_parameterization: int
    cv_frame_visible: bool
    dwg_flags1: int

class MText(Entity):
    text: str
    insertion: Tuple[float, float, float]
    height: float
"#;
    write_file(&dest.join("ocs/entities.pyi"), content);
}

fn write_ocs_stub(dest: &std::path::Path) {
    let content = r#"# Generated by ocs_python_repl/build.rs
from typing import Any, Dict, List, Optional
from ocs.entities import Entity

class _OcsDocument:
    def entities(self) -> List[Entity]: ...
    def entity(self, handle: int) -> Optional[Entity]: ...
    def layers(self) -> Dict[int, str]: ...
    def counts(self) -> Dict[str, int]: ...
    def refresh(self) -> None: ...
    def add(self, entity: Entity) -> int: ...
    def add_many(self, entities: List[Entity]) -> List[int]: ...
    def update(self, entity: Entity) -> bool: ...
    def remove(self, handle: int) -> bool: ...
    def read_record(self, handle: int, app_name: str) -> Optional[Dict[str, Any]]: ...
    def write_record(self, handle: int, record: Dict[str, Any]) -> bool: ...
    def remove_record(self, handle: int, app_name: str) -> bool: ...

doc: _OcsDocument
"#;
    write_file(&dest.join("ocs/__init__.pyi"), content);
    write_file(&dest.join("ocs/_ocs.pyi"), content);
}

fn write_py_typed(dest: &std::path::Path) {
    write_file(&dest.join("py.typed"), "");
}
