use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

include!("build/generate.rs");

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("python");
    fs::create_dir_all(&dest).unwrap();
    fs::create_dir_all(dest.join("ocs")).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build/generate.rs");
    println!("cargo:rerun-if-changed=ocs/__init__.py");
    println!("cargo:rerun-if-changed=crud_manifest.json");

    // PyO3's extension-module feature does not link libpython on Unix. On
    // macOS the linker must be told to resolve Python symbols at load time.
    pyo3_build_config::add_extension_module_link_args();

    write_repl_wrapper(&dest);
    write_startup(&dest);
    write_ocs_init(&dest);
    write_py_typed(&dest);
    write_ocs_stub(&dest);
    run_generation(&out_dir);
}

fn write_file(path: &Path, content: &str) {
    fs::write(path, content).unwrap();
}

fn run_generation(out_dir: &Path) {
    let manifest = Manifest::load();
    let registry_path = find_type_registry(&manifest);
    let registry = TypeRegistry::load(&registry_path);

    let ocs_dir = out_dir.join("python/ocs");
    fs::create_dir_all(&ocs_dir).unwrap();

    let (entities_py, entities_pyi, entity_crud_rs) = crate::generate_all(&manifest, &registry);
    write_file(&ocs_dir.join("entities.py"), &entities_py);
    write_file(&ocs_dir.join("entities.pyi"), &entities_pyi);
    write_file(&out_dir.join("entity_crud.rs"), &entity_crud_rs);
}

fn find_type_registry(manifest: &Manifest) -> PathBuf {
    let target_dir = env::var("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target"));
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let build_dir = target_dir.join(profile).join("build");

    let mut candidates = Vec::new();
    for entry in fs::read_dir(&build_dir).unwrap_or_else(|e| {
        panic!("failed to read build directory {}: {e}", build_dir.display())
    }) {
        let entry = entry.unwrap();
        let name = entry.file_name().to_string_lossy().to_string();
        if !name.starts_with("ocs_plugin_api-") {
            continue;
        }
        let path = entry.path().join("out/type_registry.json");
        if !path.exists() {
            continue;
        }
        let mtime = fs::metadata(&path)
            .and_then(|m| m.modified())
            .unwrap_or(SystemTime::UNIX_EPOCH);
        candidates.push((mtime, path));
    }

    // Prefer the newest registry that actually contains every type we need.
    // Stale/incomplete build artifacts can accumulate in the target directory,
    // and picking purely by mtime produces non-deterministic generated bindings.
    candidates.sort_by(|a, b| b.0.cmp(&a.0));
    let required: std::collections::BTreeSet<&str> = manifest
        .type_filter
        .iter()
        .map(String::as_str)
        .chain(["EntityCommon"])
        .collect();
    for (_, path) in &candidates {
        let text = fs::read_to_string(path).unwrap_or_default();
        if let Ok(registry) = serde_json::from_str::<TypeRegistry>(&text) {
            let missing: Vec<&str> = required
                .iter()
                .copied()
                .filter(|name| registry.get(name).is_none())
                .collect();
            if missing.is_empty() {
                return path.clone();
            }
            eprintln!(
                "[ocs_python_repl build] skipping stale registry {} (missing: {:?})",
                path.display(),
                missing
            );
        }
    }

    if candidates.is_empty() {
        panic!(
            "type_registry.json not found in {} for ocs_plugin_api build output",
            build_dir.display()
        )
    }

    panic!(
        "no type_registry.json in {} contains all required types: {:?}. \
         The selected ocs_plugin_api registry is missing these entity kinds. \
         If you added a new entity, ensure it is traced in ocs_plugin_api/build.rs \
         and that the change is present in the ocs_plugin_api source (git rev or local path).",
        build_dir.display(),
        required
    )
}

fn write_repl_wrapper(dest: &Path) {
    let content = r##"# Generated by ocs_python_repl/build.rs
"""Platform wrapper that launches IPython (or plain Python) in an OS terminal."""
import os
import shlex
import shutil
import signal
import subprocess
import sys
import time
import traceback

SESSION_DIR = os.path.dirname(os.path.abspath(__file__))
PYTHON = sys.executable
LOG_PATH = os.path.join(SESSION_DIR, "repl.log")
STDERR_LOG_PATH = os.path.join(SESSION_DIR, "wrapper_stderr.log")

# Redirect the wrapper's Python-level stderr to a log file so the host can read
# startup errors. On Windows the wrapper console is hidden from the start.
try:
    sys.stderr = open(STDERR_LOG_PATH, "a", encoding="utf-8")
except Exception:
    pass


def log(msg):
    try:
        with open(LOG_PATH, "a", encoding="utf-8") as f:
            f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} {msg}\n")
    except Exception:
        pass


log(f"wrapper started: python={PYTHON} platform={sys.platform}")


def check_ipython():
    try:
        import importlib.util

        return importlib.util.find_spec("IPython") is not None
    except Exception:
        return False


def make_env():
    env = os.environ.copy()
    parts = env.get("PYTHONPATH", "").split(os.pathsep)
    if SESSION_DIR not in parts:
        parts.insert(0, SESSION_DIR)
    env["PYTHONPATH"] = os.pathsep.join(parts)
    return env


def start_ipython_command():
    startup = os.path.join(SESSION_DIR, "startup.py")
    return [PYTHON, "-m", "IPython", "-i", startup]


def start_plain_command():
    startup = os.path.join(SESSION_DIR, "startup.py")
    return [PYTHON, "-i", startup]


def find_terminal():
    candidates = [
        "xterm",
        "konsole",
        "xfce4-terminal",
        "gnome-terminal",
        "alacritty",
        "kitty",
        "wezterm",
    ]
    for name in candidates:
        if shutil.which(name):
            return name
    if sys.platform == "darwin" and os.path.isdir(
        "/System/Applications/Utilities/Terminal.app"
    ):
        return "Terminal.app"
    return None


def build_terminal_command(term, cmd):
    if term == "xterm":
        return ["xterm", "-e"] + cmd
    if term == "konsole":
        return ["konsole", "-e"] + cmd
    if term == "xfce4-terminal":
        return ["xfce4-terminal", "-e", " ".join(shlex.quote(c) for c in cmd)]
    if term == "gnome-terminal":
        return ["gnome-terminal", "--"] + cmd
    if term == "alacritty":
        return ["alacritty", "-e"] + cmd
    if term == "kitty":
        return ["kitty"] + cmd
    if term == "wezterm":
        return ["wezterm", "start", "--"] + cmd
    raise RuntimeError(f"unsupported terminal: {term}")


def spawn_terminal_app(cmd, env):
    """Best-effort Terminal.app support on macOS."""
    import tempfile

    script = tempfile.NamedTemporaryFile(mode="w", suffix=".command", delete=False)
    pid_file = script.name + ".pid"

    def _cleanup():
        try:
            os.unlink(pid_file)
        except FileNotFoundError:
            pass
        except Exception:
            pass
        try:
            os.unlink(script.name)
        except FileNotFoundError:
            pass
        except Exception:
            pass

    try:
        script.write("#!/bin/sh\n")
        script.write(f"echo $$ > {shlex.quote(pid_file)}\n")
        for key, value in env.items():
            script.write(f"export {shlex.quote(key)}={shlex.quote(value)}\n")
        script.write("cd " + shlex.quote(SESSION_DIR) + "\n")
        script.write(" ".join(shlex.quote(c) for c in cmd) + "\n")
        script.write(f"rm -f {shlex.quote(pid_file)}\n")
        script.write(f"rm -f {shlex.quote(script.name)}\n")
        script.close()
        os.chmod(script.name, 0o755)

        try:
            subprocess.Popen(
                ["open", "-a", "Terminal.app", script.name], env=env
            )
        except Exception as e:
            print(f"failed to launch Terminal.app: {e}", file=sys.stderr)
            _cleanup()
            return _DummyProcess()

        # Wait for the shell inside Terminal.app to write its PID.
        for _ in range(50):
            if os.path.exists(pid_file):
                break
            time.sleep(0.1)

        if not os.path.exists(pid_file):
            _cleanup()
            return _DummyProcess()

        pid = int(open(pid_file).read())

        class Proc:
            def terminate(self):
                _kill_pid(pid, signal.SIGTERM)

            def kill(self):
                _kill_pid(pid, signal.SIGKILL)

            def wait(self):
                while True:
                    try:
                        os.kill(pid, 0)
                    except ProcessLookupError:
                        break
                    time.sleep(0.5)
                _cleanup()
                return 0

        return Proc()
    except Exception:
        _cleanup()
        raise


class _DummyProcess:
    def terminate(self):
        pass

    def kill(self):
        pass

    def wait(self):
        while True:
            time.sleep(1)


def _kill_pid(pid, sig):
    try:
        os.kill(pid, sig)
    except ProcessLookupError:
        pass
    except Exception:
        pass


def spawn_unix(cmd, env):
    term = find_terminal()
    if term is None:
        sys.exit(
            "No terminal emulator found. "
            "Install xterm, konsole, xfce4-terminal, gnome-terminal, alacritty, kitty, or wezterm."
        )
    if term == "Terminal.app":
        return spawn_terminal_app(cmd, env)
    return subprocess.Popen(build_terminal_command(term, cmd), env=env)


def install_signal_handlers(proc):
    def handler(signum, frame):
        try:
            proc.terminate()
        except Exception:
            pass
        try:
            proc.kill()
        except Exception:
            pass
        sys.exit(0)

    signal.signal(signal.SIGTERM, handler)
    signal.signal(signal.SIGINT, handler)


def install_windows_signal_handlers(proc):
    """Keep the wrapper alive while IPython handles Ctrl+C, and shut down the
    child when the host sends Ctrl+Break to the shared console."""

    def _ignore(signum, frame):
        pass

    def _shutdown(signum, frame):
        try:
            proc.terminate()
        except Exception:
            pass
        sys.exit(0)

    signal.signal(signal.SIGINT, _ignore)
    signal.signal(signal.SIGBREAK, _shutdown)


def main():
    try:
        if check_ipython():
            cmd = start_ipython_command()
            log("using IPython")
        else:
            log("IPython not found; falling back to plain Python REPL")
            print(
                "IPython not found; falling back to plain Python REPL.", file=sys.stderr
            )
            cmd = start_plain_command()

        env = make_env()
        log(f"command: {cmd}")
        log(f"PYTHONPATH: {env.get('PYTHONPATH', '')}")

        if sys.platform == "win32":
            # The host launches the wrapper with CREATE_NEW_CONSOLE, so the
            # wrapper already owns a visible console. IPython inherits that
            # console (no CREATE_NEW_CONSOLE). The wrapper ignores Ctrl+C so
            # only IPython handles it, and catches Ctrl+Break to shut down the
            # whole session when the host requests it.
            proc = subprocess.Popen(cmd, env=env)
            install_windows_signal_handlers(proc)
            log(f"spawned windows process pid={proc.pid}")
        else:
            proc = spawn_unix(cmd, env)
            try:
                with open(os.path.join(SESSION_DIR, "ipython.pid"), "w", encoding="utf-8") as f:
                    f.write(str(proc.pid))
            except Exception:
                pass
            install_signal_handlers(proc)
            log(f"spawned unix process pid={proc.pid}")

        try:
            code = proc.wait()
            log(f"child exited with code {code}")
        except KeyboardInterrupt:
            log("keyboard interrupt")
            code = 0
        sys.exit(code)
    except Exception as e:
        log(f"wrapper crashed: {e}\n{traceback.format_exc()}")
        raise


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
        sys.exit(1)
"##;
    write_file(&dest.join("repl_wrapper.py"), content);
}

fn write_startup(dest: &Path) {
    let content = r##"# Generated by ocs_python_repl/build.rs
"""Bootstrap the IPython REPL with OCS document access and magics."""
import os
import re
import shlex
import sys

_SESSION_DIR = os.path.dirname(os.path.abspath(__file__))
if _SESSION_DIR not in sys.path:
    sys.path.insert(0, _SESSION_DIR)

import ocs

_snapshot_path = os.environ.get("OCS_V4_SNAPSHOT", "")
if _snapshot_path:
    ocs.doc = ocs._init(_snapshot_path)
else:
    # Running outside the host (e.g. in tests). Provide a dummy document so
    # the module still imports and the helper functions are available.
    class _NoDocument:
        def __getattr__(self, name):
            raise RuntimeError(
                "ocs.doc is not available: run PYTHONSHELL from OpenCADStudio "
                "or set OCS_V4_SNAPSHOT to a valid snapshot path."
            )

    ocs.doc = _NoDocument()


def _pyimport(path):
    """Run a Python script in the current namespace."""
    if not os.path.isfile(path):
        print(f"pyimport: file not found: {path}", file=sys.stderr)
        return
    with open(path, "r", encoding="utf-8") as f:
        code = f.read()
    exec(code, globals())


def _pyexport(path):
    """Write the current session's input history to a file."""
    content = "# No input history available in plain Python REPL.\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Exported session to {path}")


try:
    from IPython.core.magic import register_line_magic

    @register_line_magic
    def pyimport(line):
        path = line.strip().strip('"').strip("'")
        if not os.path.isfile(path):
            print(f"pyimport: file not found: {path}", file=sys.stderr)
            return
        get_ipython().run_line_magic("run", f"-i {shlex.quote(path)}")

    @register_line_magic
    def pyexport(line):
        path = line.strip().strip('"').strip("'")
        hist = list(get_ipython().history_manager.get_range())
        cells = []
        for _session, _line, cell in hist:
            cell = cell.strip()
            if cell.startswith("%pyexport"):
                continue
            # Strip IPython continuation prompts.
            cell = re.sub(r"^\s*\.{3,}\s?", "", cell, flags=re.MULTILINE)
            cells.append(cell)
        if cells:
            content = "\n".join(cells) + "\n"
        else:
            content = "# No input history to export.\n"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Exported session to {path}")

except Exception:
    # Plain Python REPL fallback.
    def pyimport(path):
        _pyimport(path)

    def pyexport(path):
        _pyexport(path)
"##;
    write_file(&dest.join("startup.py"), content);
}

fn write_ocs_init(dest: &Path) {
    let content = r##"# Open CAD Studio Python REPL package.
# The compiled Rust extension is loaded as `ocs_python_repl` and re-exported
# under the `ocs` namespace. Generated entity classes live in `ocs.entities`.
#
# Implementation note: we replace `sys.modules[__name__]` with the extension
# module object so that `import ocs` gives users the Rust-backed `_OcsDocument`
# directly. We then set `__path__` so that `ocs.entities` still resolves to the
# generated submodule for editor tooling and type checkers.

import os
import shutil
import sys

_package_dir = os.path.dirname(os.path.abspath(__file__))
_parent_dir = os.path.dirname(_package_dir)
if _parent_dir not in sys.path:
    sys.path.insert(0, _parent_dir)

def _load_extension():
    """Load the Rust extension, coping with Windows refusing `.dll` imports."""
    try:
        import ocs_python_repl as _ocs  # type: ignore
        return _ocs
    except ImportError:
        pass

    _cdylib_path = os.environ.get("OCS_PLUGIN_CDYLIB_PATH", "")
    if not _cdylib_path or not os.path.isfile(_cdylib_path):
        raise ImportError(
            "The OCS Python extension (ocs_python_repl) is not available. "
            "Make sure the Python REPL plugin is loaded and the plugin directory "
            "is on PYTHONPATH."
        )

    # On Windows, Python's import machinery only recognises `.pyd` as an
    # extension-module suffix. Copy/hardlink the cdylib into the session dir
    # with the expected name so normal import succeeds.
    _pyd_path = os.path.join(_parent_dir, "ocs_python_repl.pyd")
    if not os.path.isfile(_pyd_path):
        try:
            os.link(_cdylib_path, _pyd_path)
        except Exception:
            shutil.copy2(_cdylib_path, _pyd_path)
    import ocs_python_repl as _ocs  # type: ignore
    return _ocs

_ocs = _load_extension()

sys.modules[__name__] = _ocs

# Keep the package path resolvable for editor tooling.
if not hasattr(_ocs, "__path__"):
    _ocs.__path__ = [_package_dir]
"##;
    write_file(&dest.join("ocs/__init__.py"), content);
}

fn write_ocs_stub(dest: &Path) {
    let content = r#"# Generated by ocs_python_repl/build.rs
from typing import Any, Dict, List, Optional
from ocs.entities import Entity

class _OcsDocument:
    def entities(self) -> List[Entity]: ...
    def entity(self, handle: int) -> Optional[Entity]: ...
    def layers(self) -> Dict[int, str]: ...
    def counts(self) -> Dict[str, int]: ...
    def refresh(self) -> None: ...
    def add(self, entity: Entity) -> int: ...
    def add_many(self, entities: List[Entity]) -> List[int]: ...
    def update(self, entity: Entity) -> bool: ...
    def remove(self, handle: int) -> bool: ...
    def read_record(self, handle: int, app_name: str) -> Optional[Dict[str, Any]]: ...
    def write_record(self, handle: int, record: Dict[str, Any]) -> bool: ...
    def remove_record(self, handle: int, app_name: str) -> bool: ...

doc: _OcsDocument
"#;
    write_file(&dest.join("ocs/__init__.pyi"), content);
    write_file(&dest.join("ocs/_ocs.pyi"), content);
}

fn write_py_typed(dest: &Path) {
    write_file(&dest.join("py.typed"), "");
}
