use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

include!("build/generate.rs");

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("python");
    fs::create_dir_all(&dest).unwrap();
    fs::create_dir_all(dest.join("ocs")).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build/generate.rs");
    println!("cargo:rerun-if-changed=crud_manifest.json");
    println!("cargo:rerun-if-changed=templates/repl_wrapper.py");
    println!("cargo:rerun-if-changed=templates/startup.py");
    println!("cargo:rerun-if-changed=templates/ocs/__init__.py");
    println!("cargo:rerun-if-changed=templates/ocs/__init__.pyi");
    println!("cargo:rerun-if-changed=templates/py.typed");

    // PyO3's extension-module feature does not link libpython on Unix. On
    // macOS the linker must be told to resolve Python symbols at load time.
    // On Linux the OCS plugin runner (not Python) loads this cdylib first, so
    // defer Python symbol resolution until the Python child actually uses them.
    pyo3_build_config::add_extension_module_link_args();
    #[cfg(target_os = "linux")]
    {
        println!("cargo:rustc-link-arg=-Wl,-z,lazy");
    }

    write_repl_wrapper(&dest);
    write_startup(&dest);
    write_ocs_init(&dest);
    write_py_typed(&dest);
    write_ocs_stubs(&dest);
    run_generation(&out_dir);
}

fn write_file(path: &Path, content: &str) {
    fs::write(path, content).unwrap();
}

fn write_repl_wrapper(dest: &Path) {
    write_file(
        &dest.join("repl_wrapper.py"),
        include_str!("templates/repl_wrapper.py"),
    );
}

fn write_startup(dest: &Path) {
    write_file(&dest.join("startup.py"), include_str!("templates/startup.py"));
}

fn write_ocs_init(dest: &Path) {
    let ocs_dir = dest.join("ocs");
    fs::create_dir_all(&ocs_dir).unwrap();
    write_file(
        &ocs_dir.join("__init__.py"),
        include_str!("templates/ocs/__init__.py"),
    );
}

fn write_ocs_stubs(dest: &Path) {
    let ocs_dir = dest.join("ocs");
    fs::create_dir_all(&ocs_dir).unwrap();
    let stub = include_str!("templates/ocs/__init__.pyi");
    write_file(&ocs_dir.join("__init__.pyi"), stub);
    write_file(&ocs_dir.join("_ocs.pyi"), stub);
}

fn write_py_typed(dest: &Path) {
    write_file(&dest.join("py.typed"), include_str!("templates/py.typed"));
}

fn run_generation(out_dir: &Path) {
    let manifest = Manifest::load();
    let registry_path = find_type_registry(&manifest);
    let registry = TypeRegistry::load(&registry_path);

    let ocs_dir = out_dir.join("python/ocs");
    fs::create_dir_all(&ocs_dir).unwrap();

    let (entities_py, entities_pyi, entity_crud_rs) = crate::generate_all(&manifest, &registry);
    write_file(&ocs_dir.join("entities.py"), &entities_py);
    write_file(&ocs_dir.join("entities.pyi"), &entities_pyi);
    write_file(&out_dir.join("entity_crud.rs"), &entity_crud_rs);

    write_counts_mapping(out_dir, &manifest);
}

fn write_counts_mapping(out_dir: &Path, manifest: &Manifest) {
    let mut arms = String::new();
    for kind in &manifest.type_filter {
        arms.push_str(&format!(
            "        acadrust::EntityType::{kind}(_) => \"{kind}\",\n"
        ));
    }
    let content = format!(
        "// Generated by build.rs from crud_manifest.json type_filter.\n\
         // Maps EntityType variants to their Python-facing kind names.\n\
         fn entity_kind_name(entity: &acadrust::EntityType) -> &'static str {{\n\
             match entity {{\n{arms}        _ => \"Other\",\n    }}\n}}\n"
    );
    write_file(&out_dir.join("counts_mapping.rs"), &content);
}

fn find_type_registry(manifest: &Manifest) -> PathBuf {
    let target_dir = env::var("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target"));
    let profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let build_dir = target_dir.join(profile).join("build");

    let mut candidates = Vec::new();
    for entry in fs::read_dir(&build_dir).unwrap_or_else(|e| {
        panic!("failed to read build directory {}: {e}", build_dir.display())
    }) {
        let entry = entry.unwrap();
        let name = entry.file_name().to_string_lossy().to_string();
        if !name.starts_with("ocs_plugin_api-") {
            continue;
        }
        let path = entry.path().join("out/type_registry.json");
        if !path.exists() {
            continue;
        }
        let mtime = fs::metadata(&path)
            .and_then(|m| m.modified())
            .unwrap_or(SystemTime::UNIX_EPOCH);
        candidates.push((mtime, path));
    }

    // Prefer the newest registry that actually contains every type we need.
    // Stale/incomplete build artifacts can accumulate in the target directory,
    // and picking purely by mtime produces non-deterministic generated bindings.
    candidates.sort_by(|a, b| b.0.cmp(&a.0));
    let required: std::collections::BTreeSet<&str> = manifest
        .type_filter
        .iter()
        .map(String::as_str)
        .chain(["EntityCommon"])
        .collect();
    for (_, path) in &candidates {
        let text = fs::read_to_string(path).unwrap_or_default();
        if let Ok(registry) = serde_json::from_str::<TypeRegistry>(&text) {
            let missing: Vec<&str> = required
                .iter()
                .copied()
                .filter(|name| registry.get(name).is_none())
                .collect();
            if missing.is_empty() {
                return path.clone();
            }
            eprintln!(
                "[ocs_python_repl build] skipping stale registry {} (missing: {:?})",
                path.display(),
                missing
            );
        }
    }

    if candidates.is_empty() {
        panic!(
            "type_registry.json not found in {} for ocs_plugin_api build output",
            build_dir.display()
        )
    }

    panic!(
        "no type_registry.json in {} contains all required types: {:?}. \
         The selected ocs_plugin_api registry is missing these entity kinds. \
         If you added a new entity, ensure it is traced in ocs_plugin_api/build.rs \
         and that the change is present in the ocs_plugin_api source (git rev or local path).",
        build_dir.display(),
        required
    )
}

