# Generated from templates/ocs/__init__.pyi by ocs_python_repl/build.rs
from typing import Any, Dict, List, Optional
from ocs.entities import Entity

class _OcsDocument:
    def entities(self) -> List[Entity]: ...
    def entity(self, handle: int) -> Optional[Entity]: ...
    def layers(self) -> Dict[int, str]: ...
    def counts(self) -> Dict[str, int]: ...
    def refresh(self) -> None: ...
    def add(self, entity: Entity) -> int: ...
    def add_many(self, entities: List[Entity]) -> List[int]: ...
    def update(self, entity: Entity) -> bool: ...
    def remove(self, handle: int) -> bool: ...
    def read_record(self, handle: int, app_name: str) -> Optional[Dict[str, Any]]: ...
    def write_record(self, handle: int, record: Dict[str, Any]) -> bool: ...
    def remove_record(self, handle: int, app_name: str) -> bool: ...

doc: _OcsDocument
